### ISSUE TITLE
Pass unread file contents to `rc`

### ISSUE THREAD

**Issue by petersohn** [lyuts/vim-rtags#12]
`rc` supports the `--unsaved-file` flag that allows queries to be done in an unsaved file. It would be nice if this feature was integrated in vim-rtags.

**Comment by martong** [comment]
+1
(But this is rather an enhancement than an issue.)

**Comment by lyuts** [comment]
Agree, will look into integrating it.

**Comment by lyuts** [comment]
I made an initial draft of this improvement. For now keeping it in a separate branch until we are confident with pushing it out:

https://github.com/lyuts/vim-rtags/tree/unsaved_file_support

If you want, you could give it a try, or wait when we merge it into master.

**Comment by lyuts** [comment]
Merged this functionality to master.
