### ISSUE TITLE
vim-rtags continued support

### ISSUE THREAD

**Issue by mckellyln** [lyuts/vim-rtags#126]
Hi,
@lyuts are you around ?
I use vim-rtags every day and it is awesome and I just cannot thank you enough for it.
I will continue to support and update vim-rtags from my fork, ok ?
thank you again,
-m

**Comment by mckellyln** [comment]
My repo is at:
https://github.com/mckellyln/vim-rtags.git
I have not yet tested my changes with nvim (only vim).

**Comment by mckellygit** [comment]
Hi,
My forked repo has been moved to:
https://github.com/mckellygit/vim-rtags
I've made sure it works with nvim as well.
I will continue to support this as I can.
thx,
-m
