### ISSUE TITLE
Make RtagsFindSymbols use tab-completion

### ISSUE THREAD

**Issue by petersohn** [lyuts/vim-rtags#18]
`RtagsFindSymbols` uses `rc -F`, which finds symbols based on exact name match. It would be useful to be able to search based on prefix. `rc -S` lists symbols starting with its argument. It would be useful to make `RtagsFindSymbols` tab-complete based on the result of `rc -S`.

**Comment by lyuts** [comment]
AFAIU, the merged change doesn't completely corresponds to the requested feature. @petersohn, correct me if I wrong, you want to be able to auto complete RtagsFindSymbols arguments by intermediately invoking ```rc -S```?

**Comment by lyuts** [comment]
I'm sorry, I've reread the docs for customlist completion and it looks like it indeed matches the desired behavior.

**Comment by petersohn** [comment]
Yes, it seems to do what I need.
