### ISSUE TITLE
Is there a way to run rc for the whole project as a neovim job?

### ISSUE THREAD

**Issue by sztomi** [lyuts/vim-rtags#27]
I would like my project to be reindexed periodically in the background. Is this possible? It it something that vim-rtags already does?

**Comment by lyuts** [comment]
```rtags``` does that for you by reindexing files that have changed. You also have an option to run ```rc -V``` which will trigger reindexing of entire project. ```vim-rtags``` currently has a mapping to only reindex a given file (```rc -V /path/to/some/file```), though we can add a mapping for ```rc -V```.
However, it seems to me that there should be no reason to invoke reindexing from ```vim-rtags``` as ```rtags``` detection of files being changed and reindexing them on the fly should be sufficient not needing to do periodic reindexing.

**Comment by sztomi** [comment]
What if I add new file to the project (i.e. new entry in the compilation database)?

**Comment by lyuts** [comment]
That shouldn't be a problem. Of course, once you add a new file ```rtags``` doesn't know anything about it. But as soon as you try compiling your code with this file ```rtags``` will start tracking it as a part of the project.

**Comment by sztomi** [comment]
Great, thank you!
