### ISSUE TITLE
make location-list window height based on number of entries

### ISSUE THREAD

**Issue by rajukv** [lyuts/vim-rtags#31]
I was wondering if the height of the location-list that shows the results can be configured. I think the default height is 10 lines, but if I have only 3 lines of results, having a location list of 10 lines consumes screen space. Would it be possible to change the height of location list based on number of results? It might also be useful to provide a way for user to configure the height of location list for showing the results.

**Comment by lyuts** [comment]
@rajukv, I think this doable. ```lopen``` takes an optional parameter which defines its height. I'll add both, max height configuration and handling the case you describe.

**Comment by lyuts** [comment]
Added parameter controls the height of the window. Parameter is common for both location list and quickfix list. At this point don't see a use case for them to have different heights.

**Comment by rajukv** [comment]
@lyuts thank you. I am closing this issue
