### ISSUE TITLE
+python is not needed

### ISSUE THREAD

**Issue by jmacdonagh** [lyuts/vim-rtags#37]
Since 754ad203e4f993850d2772155f6e38398def86b0, it does not appear that `+python` is needed. In the current `master`, the only function that needs it is `Offset2LineCol`, and that function isn't called anymore since `rc` changed their output format (as fixed in 754ad203e4f993850d2772155f6e38398def86b0).

Requiring this isn't too big of a deal, except that Ubuntu 16.04's vim seems to only have `+python3`.

**Comment by lyuts** [comment]
That's right, good find. Cleaned that up. Thank you.

**Comment by jmacdonagh** [comment]
Thanks! You'll need to remove this condition too:

https://github.com/lyuts/vim-rtags/blob/master/plugin/rtags.vim#L2

**Comment by jmacdonagh** [comment]
@lyuts, can you remove the check I mentioned above? It's not needed and will break newer `python3` vim builds. Thanks!

**Comment by lyuts** [comment]
Ah, missed that. It is now gone (a2686008795a9ab4822cd6f4a7013fbdffad639a).
