### ISSUE TITLE
Plugin should not send buffer as --unsaved-file unless needed

### ISSUE THREAD

**Issue by jmacdonagh** [lyuts/vim-rtags#38]
Sending the buffer contents using `--unsaved-file` is unnecessary if the buffer has no unsaved changes. `rdm` tracks and re-indexes any saved files.

I've been using vim-rtags to browse a very large source code base (no changes, being made, just read only). Any time I follow links or find references it's delayed as `rdm` has to reindex the potentially large file (way worse when it's a header file used by many source files).

It would be nice if this were configurable. An option that takes 3 states:

* `eager` would perform the current behavior, always feeding in the buffer before executing the actual `rc` command. This is useful if `rdm`'s file watch isn't working and missed a saved change.
* `conservative` would be the default and would only feed in the buffer is there are unsaved changes
* `none` would never feed in the buffer's contents. This is useful if you accidentally make a change to a file when you're only trying to browse the source code and try to follow a reference. This would be a way to ensure that vim-rtags does not interfere with the index.

Don't know if you have any thoughts on this. I was going to implement this, but I was wondering if you had other plans.

**Comment by bagnose** [comment]
You may be interested in https://github.com/acres-com-au/vim-rtags/commit/2871d868df58d00ea58ac8e539dd30c15da9456a

**Comment by jmacdonagh** [comment]
@bagnose, that looks like exactly what I was looking for. I'll check with the author and see if they'll put in a pull request. Great find!

**Comment by jmacdonagh** [comment]
@quixotique, are you able to create separate pull requests for the two useful commits commits you've made to vim-rtags (specifically https://github.com/acres-com-au/vim-rtags/commit/2871d868df58d00ea58ac8e539dd30c15da9456a)?

**Comment by quixotique** [comment]
Just created pull request #39

**Comment by jmacdonagh** [comment]
Thanks @quixotique!

**Comment by lyuts** [comment]
Pull request #39 is now merged.
