### ISSUE TITLE
Plugin send buffer as --unsaved-file cause rdm update almost all project.

### ISSUE THREAD

**Issue by pangchol** [lyuts/vim-rtags#40]
I find send buffer as --unsaved-file command to rdm can cause rdm update almost all project sometimes. this may cause by the file is This file is dependent on a lot of other files. this action cause very bad function problam because update a big project will use up all cpu resourse in a long time. Worse, every time jump to the same file will trigger the entire project update.

**Comment by lyuts** [comment]
This seems like #38 which has fixed by pull request #39.
