### ISSUE TITLE
Jump to definition or declaration

### ISSUE THREAD

**Issue by dpelle** [lyuts/vim-rtags#42]
The vim rtags plugin is very useful for browsing c++ code. Thanks.
In the current implementation \<leader\>rj jumps either to the definition or to the declaration as follows:

- pressing \<leader\>rj where a symbol is used or on a declaration jumps to the definition
- pressing \<leader\>rj on a definition jumps to the declaration

I find this a bit confusing as there is a state. It also causes me to press \<leader\>rj twice if I want to jump to a declaration when cursor is where a symbol is used.  I wish there were instead 2 mappings:

- one mapping to jump to definition 
- another one to jump to declaration

Is that possible?

**Comment by lyuts** [comment]
I personally don't think that the way &lt;leader&gt;rj mapping works is confusing. It is usually called context search and works fine in most cases.

Case | Cursor location | Mapping action
---- | --------------------- | ---------------
1 | declaration | jump to definition
2 | definition | jump to declaration
3 | usage | jump to definition 

While it is possible to have a separate mapping for jumping to a declaration and a different mapping for jumping to a definition it seems like it would be an overkill. JumpTo has 4 variants: regular, split, vertical split and tab. I'm not sure we want 4 new mappings to cover jump-to-declaration case. AFAIU, the only issue you are having is 3rd case and only when you intend to jump to a declaration.
How do you workaround this right now?
I'm fine with adding a single mapping for jumping to declaration which will open that in the same window.

**Comment by lyuts** [comment]
Let me know if this works for you.

**Comment by dpelle** [comment]
> Let me know if this works for you.

Sorry for the late response, I did not see your comment earlier.  I got the latest version of plugin with the new <Leader>rJ mapping.  Thanks. It works fine for me.

I often want to jump to the declaration directly (rather than first definition, then declaration), as the documentation is near the declaration in the code that I'm working on.

**Comment by lyuts** [comment]
Thanks for finding typos. I can fix them, or you can fix them and send a pull request if you would like. Problem found, problem solved. Thank you.

**Comment by lyuts** [comment]
Typos fixed. Thanks for filing.
