### ISSUE TITLE
libclang.so.3.7: cannot open shared object file

### ISSUE THREAD

**Issue by agauniyal** [lyuts/vim-rtags#46]
`No such file or directory`.

```
~ ❯ clang --version
clang version 3.8.1 (tags/RELEASE_381/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

So what should I do here?

**Comment by lyuts** [comment]
At which point do you get 'No such file or directory' error?

**Comment by agauniyal** [comment]
I'm not using vim-rtags atm, but as far as I remember it was either at the start of vim or when firing any vim-rtags command.

**Comment by lyuts** [comment]
How are you compiling rtags? Do you by any chance use not system clang? I.e. its libraries are not in ld library path?

**Comment by agauniyal** [comment]
I use arch linux so the installation process was through aur. I didn't changed any config later after installation so I'm not sure if it was using system clang or something else. However I did had clang 3.8 at that time, and the error message was for `libclang.so.3.7`.

**Comment by lyuts** [comment]
Can you show me your ```cmake``` invocation?

**Comment by lyuts** [comment]
I'm not sure this is still relevant. I'm closing, but feel free to reopen if you have questions.
