### ISSUE TITLE
Proper completion

### ISSUE THREAD

**Issue by kenny1847** [lyuts/vim-rtags#61]
Currently we have no compleion after namespaces ('::'), only followwed by '.' and '->', and there bad filter (probably rtags problem).

**Comment by marxin** [comment]
You are right, I'm working on that. For more information please take a look here:
https://github.com/Andersbakken/rtags/issues/584

**Comment by marxin** [comment]
It's done, there's still room for improvement, but key smart completion works fine.
Can you @lyuts please close this issue?

**Comment by lyuts** [comment]
Thank you.
