### ISSUE TITLE
Failed to run asynchronously under Neovim

### ISSUE THREAD

**Issue by skt041959** [lyuts/vim-rtags#62]
Hi lyuts,
When I try to use `<Leader>rj`, I got this error message.

> Error detected while processing function rtags#HandleResults:
> line    3:
> E484: Can't open file /tmp/neovim_async_rtags.tmp.7379.0

**Comment by lyuts** [comment]
I think i have a fix for this. Quick question, which shell are you using?

**Comment by skt041959** [comment]
Csh and zsh. I don't remember which one it is when I got this issue.
