### ISSUE TITLE
using 'normal' instead of 'normal!'

### ISSUE THREAD

**Issue by P4Cu** [lyuts/vim-rtags#71]
This will cause user mappings to modify result of the script which is BAD!
for example using a plugin which maps 'm' to move causes jumplist not to be filled.

I'll commit a fix for that in a minute.

**Comment by P4Cu** [comment]
https://github.com/lyuts/vim-rtags/pull/72

**Comment by lyuts** [comment]
Thank you for the fix. It is now merged.
