### ISSUE TITLE
Location list becomes empty after jumping to one of the targets

### ISSUE THREAD

**Issue by cheshire** [lyuts/vim-rtags#81]
Vim-RTags commands such as "find symbols" or "find references" populate the location list with all the results from rtags.
However, for me, after selecting and jumping to one of those targets the location list becomes empty again, making it very hard to e.g. iterate over all usages of a function.

**Comment by cheshire** [comment]
The issue was interference with ALE plugin, since by default in its wisdom it updates location list on every new file.

**Comment by mellery451** [comment]
having this same issue...so is there a way to make ALE and rtags play nicely together?
