### ISSUE TITLE
Python 3 support requirement

### ISSUE THREAD

**Issue by mpark** [lyuts/vim-rtags#86]
It seems that https://github.com/lyuts/vim-rtags/commit/68d8bb3f9ecb4cf42856ea9810fb510ebad2868f have introduced a Python 3 requirement. I've just changed `python3` at https://github.com/lyuts/vim-rtags/blob/master/plugin/rtags.vim#L92 to be simply `python`, and it's been working fine for me so far. Is the `python3` dependency required and/or desired..?

**Comment by kmhofmann** [comment]
Yep, the 'python3' bit breaks the plugin for me. Replacing with 'python' at least doesn't give me any error messages at vim start.

**Comment by lyuts** [comment]
I myself got bitten by this and had to patch locally with to use python 2. I didn't find anything python3 specific in marxin@'s commit, so seems it should be safe to make this change e92265d.
