### ISSUE TITLE
Redraw is needed after every command

### ISSUE THREAD

**Issue by sakhnik** [lyuts/vim-rtags#9]
Whenever a command is issued (<leader>rs, for instance), there's lots of artefacts left on screen if `rdm` is running in the same terminal. Until :redraw! is executed. Consider redrawing screen after every command invocation.

**Comment by lyuts** [comment]
Is there a reason you are running rdm in the same terminal? It seems like this is not a problem with the plugin, but a problem with the fact that rdm outputs to the same stdout, which leads to these artifacts. I don't think making unconditional redraw is necessary.
As an alternative, if you really need to run rdm in the same terminal, it feels like you don't care about its output, then redirect its output to ```/dev/null```.
Open for comments and discussion.

**Comment by sakhnik** [comment]
Right, I agree.
