### ISSUE TITLE
vim8 can't work 

### ISSUE THREAD

**Issue by jh3mail** [lyuts/vim-rtags#94]
Error detected while processing function 
rtags#InitPython:

line    9:

Traceback (most recent call last):

  File "<string>", line 6, in <module>

  File "C:\\Users\\Administrator\\.cache\\vimfiles\\re
pos\\github.com\\lyuts\\vim-rtags\\plugin\vimrtags
.py", line 7, in <module>

    logging.basicConfig(filename='/tmp/vim-rtags-p
ython.log',level=logging.DEBUG)

  File "C:\Python27\Lib\logging\__init__.py", line 
1547, in basicConfig

    hdlr = FileHandler(filename, mode)

  File "C:\Python27\Lib\logging\__init__.py", line 913,

**Comment by pangchol** [comment]
this cause by "/tmp/vim-rtags-p" , the windows has not the "/tmp" dir,  you can delete the "/tmp/" to let the log file in current dir or other dir is exist in windows. By the way, I just, using rtags in linux, have you already config the rtags compatable with windows? is every thing ok? if true, could you write a course on the internet to teach us.

**Comment by jh3mail** [comment]
thanks~
